# LIGHTWEIGHT PRODUCTION WEB SERVER CONTAINER FOR LISTEN360
FROM nginx:alpine

# COPY FRONTEND STATIC ASSETS TO NGINX HTML DIRECTORY
COPY . /usr/share/nginx/html

# EXPOSE HTTP PORT 80
EXPOSE 80

# START NGINX SERVER
CMD ["nginx", "-g", "daemon off;"]
